global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"
 
 
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s 
    metrics_path: /monitoring/prometheus/metrics 
    static_configs:
      - targets: ['humor-prediction-09b81c047ba6.herokuapp.com'] 